### ISSUE TITLE
Admin : The fox theme options should be renamed as Titan Theme Options on the backend

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#1]
![image](https://cloud.githubusercontent.com/assets/12791909/10535363/f323ddfa-7414-11e5-896b-395b44249d17.png)

**Comment by Santosh-titan** [comment]
We can't change default the menu name.

**Comment by ermatitan** [comment]
The fox label has been renamed before to Titan Option.
