### ISSUE TITLE
Sponsor/Partners carousel settings max number of sponsor/partner to load per line only allows 5 , design shows 8.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#10]
PSD Design
![image](https://cloud.githubusercontent.com/assets/12791909/10538318/56fa74be-742a-11e5-97f4-30c6641d35d3.png)

Sponsor/Partner settings:
![image](https://cloud.githubusercontent.com/assets/12791909/10538347/8067e0e8-742a-11e5-96a0-947bf1c0acb9.png)

**Comment by Santosh-titan** [comment]
There are some disadvantages in theFox theme. we don't have option to give more than 5  logos per line
