### ISSUE TITLE
What We Do Single page - sidebar contact us not aligned with featured image content. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#26]
![image](https://cloud.githubusercontent.com/assets/12791909/10568959/bddfc8d6-7651-11e5-8e4a-7aeb7e8f31cb.png)

**Comment by ermatitan** [comment]
not fix. please move a little higher

**Comment by Santosh-titan** [comment]
I think it was fixed now
see the attachment
![sidebar](https://cloud.githubusercontent.com/assets/13828562/11139662/3039891c-89f8-11e5-88e3-46b3f70cd94d.JPG)
