### ISSUE TITLE
Homepage - banner headline were cut when browser is re-sized.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#32]
![image](https://cloud.githubusercontent.com/assets/12791909/10569468/0550a06c-7659-11e5-9499-3cacba5021e6.png)

**Comment by ermatitan** [comment]
Not Fix. Banner and Header is not responsive. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/12791909/11081971/3fcb03d0-885c-11e5-9b8e-d240414d1a79.png)

**Comment by Santosh-titan** [comment]
Can i use custom post slider for home and inner pages? so that i can fix this issues

**Comment by ermatitan** [comment]
Hello Santosh, just ask input from your Team Lead or Manager about the issue. Thanks
