### ISSUE TITLE
Mobile : Banner description was aligned left instead of center.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#34]
Ipad Air - landscape
S4 - Landscape
iTouch
![image](https://cloud.githubusercontent.com/assets/12791909/10570440/8bc4f94c-7666-11e5-82ae-399e66d7f6a8.png)

**Comment by Santosh-titan** [comment]
Revolution slider won't work properly in browser re-flow. Please refresh the page in this ports

**Comment by ermatitan** [comment]
The clippings occurs during mobile navigation is not acceptable. There should be some way to fix this issue. Please fix. Thanks
