### ISSUE TITLE
General - Page default background were displayed at the bottom of the page.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#50]
![about us - evolv networks 2015-10-19 16-21-08](https://cloud.githubusercontent.com/assets/12791909/10572825/1233d4b4-767e-11e5-90ec-b9f91453f10a.png)

**Comment by Santosh-titan** [comment]
As per the design background image should be bottom of the page

**Comment by ermatitan** [comment]
not fix

**Comment by Santosh-titan** [comment]
As per design it should be in bottom of the page. Please tell me where do you want me to display the background image, I need clarity
see the design that i have
![02a-evo-about-us](https://cloud.githubusercontent.com/assets/13828562/11139459/78c789d4-89f5-11e5-8efd-b8ceae9f5595.jpg)
