### ISSUE TITLE
Contact Us - Message field label goes center after creating an error in submission

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#62]
IE , Firefox
![image](https://cloud.githubusercontent.com/assets/12791909/10596078/788f120c-7712-11e5-8c01-83b9d51b169f.png)

**Comment by ermatitan** [comment]
cannot verify due to issue #76 . Other error message won't appear.

**Comment by Santosh-titan** [comment]
Issues #76 has been fixed you can test is now
