### ISSUE TITLE
Where should portfolio and staff member custom post be displayed on the front-end?

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#67]
![image](https://cloud.githubusercontent.com/assets/12791909/10596501/7219525c-7717-11e5-9ac0-2852a2196006.png)

**Comment by Santosh-titan** [comment]
Portfolio and staff member custom post are created in theFox theme plugin. we can not remove theme default plugin.
![plugins](https://cloud.githubusercontent.com/assets/13828562/10723191/5d01d1c0-7bde-11e5-978a-b1dfba6f1c99.JPG)

**Comment by Santosh-titan** [comment]
We are not using this default theme custom posts in front-end
