### ISSUE TITLE
Please remove images with shutterstock watermarked. As per Titan standard, do not used images with watermarked.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#82]
https://knowledgebase.titanweb.com.au/implementation-practices/page-section-contents/using-images

![image](https://cloud.githubusercontent.com/assets/12791909/11084861/480d967e-887b-11e5-9fe5-1e71cbe15f7b.png)

**Comment by Santosh-titan** [comment]
AS per PSD design i have used this images. Any way i have removed all those images from all posts.
