### ISSUE TITLE
Mobile : Live Chat window not displayed on mobile devices.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#84]
Ipad Air , S4, ITouch

![image](https://cloud.githubusercontent.com/assets/12791909/11085136/ce24ade0-887d-11e5-9f09-33fb277853f8.png)

**Comment by Santosh-titan** [comment]
This plugin is working fine in browser re-flow but its not working in devices. I went through the plugin settings but there is no option to enable the chat for mobile devices, Please suggest me which plugin should i use for live chat. There are some plugin but as per KB standers we should not use third party plugins. need your suggestion on this

**Comment by ermatitan** [comment]
Hello Santosh, I can't suggest what plugin to used, but you can ask your Team Lead or Manage for this issue. Thanks

**Comment by Santosh-titan** [comment]
Hi @ermatitan,
I have discussed with Jolene, no need the chat feature on mobile devices
