### ISSUE TITLE
Clarrification on IT Support Services custom post.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#95]
IT Support Services is a custom post design with a custom post item "Cloud Services and etc.
A Cloud Services custom post were also available with different items under it.

Accessing Cloud services via "IT Support Services" listing page  will not direct to the Cloud Services listing page since it is design as a custom post. 

Question: Is it possible to make the items/post on IT Support Services as a post Category so that each item/post under them will still be connected through breadcrumbs.

**Comment by Santosh-titan** [comment]
Please go through this ticket so you can understand how jolene want me to display
https://projects.titanweb.com.au/public/index.php?path_info=projects/evolv-networks-pty-ltd-pack1-ct-contract/tasks/26
