### ISSUE TITLE
Why choose us page and its child pages no longer displayed on main menu navigation. Does this pages will no longer be included in the main menu navigation?

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolv-Networks#98]
![image](https://cloud.githubusercontent.com/assets/12791909/11332778/863d8198-9203-11e5-9128-557c76abc123.png)

**Comment by Santosh-titan** [comment]
As per Jolene request i made CMS changes see the ticket here
https://projects.titanweb.com.au/public/index.php?path_info=projects/evolv-networks-pty-ltd-pack1-ct-contract/tasks/26
